[[redirects]]
  from = "/api/*"      # No redirigir las rutas de la API
  to = "/api/:splat"   # Permite que las rutas de la API se manejen correctamente
  status = 200          # Este es el código de estado que queremos para la API
  force = true

[[redirects]]
  from = "/*"          # Redirigir todas las demás rutas
  to = "/index.html"   # Redirigir a index.html para rutas que no sean de la API
  status = 200          # Este es el código de estado para rutas SPAs
  force = true
